spring:
  output:
    ansi:
      enabled: always
  banner:
    location: classpath:banner/banner.txt
  main:
    banner-mode: console

  profiles:
    active: dev
  application:
    name: space_management

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /docs

server:
  port: 8000
  servlet:
    context-path: /v1


logging:
  level:
    root: info
    org:
      springframework: warn
      boot: error
      data:
        redis: debug
  pattern:
    console: '%n %d{HH:mm:ss} | %highlight(%-5level) | %cyan(%logger{30}) | %msg'
